const express = require('express')
const { get } = require('../controllers/index')
const authRouter = require('./auth')
const backofficeRouter = require('./backoffice')
const userRouter = require('./users')
const categoriesRouter = require('./categories')
const newsRouter = require('./news')
const organizationsRouter = require('./organizations')
const slidesRouter = require('./slides')
const activitiesRouter = require('./activities')
const contactsRouter = require('./contacts')
const testimonialsRouter = require('./testimonials')
const membersRouter = require('./members')
const commentsRouter = require('./comments')

const router = express.Router()

// example of a route with index controller get function
router.get('/', get)
router.use('/auth', authRouter)
router.use('/backoffice', backofficeRouter)
router.use('/users', userRouter)
router.use('/categories', categoriesRouter)
router.use('/comments', commentsRouter)
router.use('/contacts', contactsRouter)
router.use('/news', newsRouter)
router.use('/organization', organizationsRouter)
router.use('/slide', slidesRouter)
router.use('/activities', activitiesRouter)
router.use('/contacts', contactsRouter)
router.use('/testimonials', testimonialsRouter)
router.use('/members', membersRouter)
router.use('/comments', commentsRouter)

module.exports = router
